### ISSUE TITLE
Being absent minded, misses last spoken item

### ISSUE THREAD

**Issue by mjlill** [project-alice-powered-by-snips/ProjectAlice#104]
If I ask her repeat / say again she brings items forward from several previous request. Example is,  I asked for the time, then ask about ISS followed by asking for a joke. So when I asked her say again to hear the joke, she repeated the time.  It is as if some items are no longer captured in last spoken string. I really hate loosing out on those good jokes and useless facts :)

**Comment by mjlill** [comment]
Sample 
was asked to say "The space station is at -50 latitude 2 longitude over the South Atlantic Ocean"
captured text "say again"
detected intent mjlill:RepeatThis
was asked to say "What??"

**Comment by Psychokiller1888** [comment]
Most likely too low confidence score for "say again" capture
