### ISSUE TITLE
Improve versioning

### ISSUE THREAD

**Issue by Psychokiller1888** [project-alice-powered-by-snips/ProjectAlice#114]
We have to improve versioning to at least 3 digits support `x.x.x aka 1.2.3`

- First X represents main branch releases
- Second X represents updates to that said main release
- Third X represents hotfixes to the branch updates

This system no longer supports a simple greater or lower than comparison but is much more flexible. **This has to extend to modules as well**. 

- Alpha versioning: by adding "-a" at the end, `2.0.0-a` `2.0.0-a4`
- Beta versioning: by adding "-b" at the end, `3.0.0-b` `3.0.0-b1`
- Release candidate versioning: by adding "-rc" at the end, `3.0.0-rc` `3.0.0-rc2`

Alpha, Beta and RC are only to be applied to main branches, such as `1.0.0-b` or `2.0.0-b` or `1.0.0-rc`

We have to respect a clear process for versioning and be clear with the community what alpha, beta and rc means:

- An alpha released a a risky release where things move and get broken easily, where we offer minimal support because we are working on it and things can change within hours. It is mainly targeted to people wanting to help try out new features
- A beta is a more stable release of an alpha. It's a snapshot of the alpha branch when we feel like it is stable. Releasing a beta doesn't mean the work on alpha is ended if we still have major plans. It is targeted to people want to try out new features and give their feedbacks to devs to improve Alice before a major release
- An RC is targeted to people wanted to try out Alice a bit before the others at minimal risks. Once an RC hits the downloads, alpha and beta branches must be closed and shouldn't evolve anymore. No more new features, no more additions, just hotfixes increasing the `-rc` numbering
- A major release is ready for everybody. We offer support for it and take enhancements and feature requests into consideration for either the next major release or the next update.

- Hotfixes don't need team discussion and can be singely made if they don't require deep changes
- Updates in functionality do and don't need discussion in team. If you are adding a "earth quake sensor" to the Telemetry module, just do it, won't change anything. If you plan to rework the assistant download flow we have to discuss it openly on discord. Openly means in the dev channels, so people see on what we are coding and can even provide inputs and thoughts.
- Major release **have to be planned and discussed**, these changes can impact the whole project and the way we are heading.

Modules have to follow the same versioning convention, while keeping the min Alice version

**Comment by maxbachmann** [comment]
yeah we already talked about this a while back since we absolutely need this
