### ISSUE TITLE
localize vs getTranslation

### ISSUE THREAD

**Issue by maxbachmann** [project-alice-powered-by-snips/ProjectAlice#51]
in the Module DateTimeYear currently the function localize is used for the translation of some strings. However the strings are in the system strings.json while localize accesses the system wide talk files.
So the modules should probably use getTranslation for these translations. Another issue here is that these string.json files do not include weekday translations even though they are used by the module.

What is the localize function even supposed to do? When is it required to translate a talk sentence (where the language is not already clear in front -> you can use the normal randomTalk). Maybe a small comment in the code would help clearing this up

**Comment by philipp2310** [comment]
For copy-pasta:
`{
	"Monday":{
		"en": "Monday",
		"de": "Montag",
		"fr": "Lundi"
		},
	"Tuesday":{
		"en": "Tuesday",
		"de": "Dienstag",
		"fr": "Mardi"
		},
	"Wednesday":{
		"en": "Wednesday",
		"de": "Mittwoch",
		"fr": "Mercredi"
		},
	"Thursday":{
		"en": "Thursday",
		"de": "Donnerstag",
		"fr": "Jeudi"
		},
	"Friday":{
		"en": "Friday",
		"de": "Freitag",
		"fr": "Vendredi"
		},
	"Saturday":{
		"en": "Saturday",
		"de": "Samstag",
		"fr": "Samedi"
		},
	"Sunday":{
		"en": "Sunday",
		"de": "Sonntag",
		"fr": "Dimanche"
		}
}`

**Comment by Psychokiller1888** [comment]
Localize is to switch between different ways of saying in different language, exchange "." against ",",  and other cases. Talk means getting a string as an answer for a module / manager. Translation is needed for some cases where you need to switch based on what a user said.

Let's take the Yes / No, in french Oui / Non and german Ja / Nein (Da / Niet etc etc) . This was made before traversing the slot for real value was possible and can easily be replaced with our slot structure that has the main value always in english

**Comment by maxbachmann** [comment]
hm why does it use langData from the TalkManager then? I thought that should include the talk files only

**Comment by Psychokiller1888** [comment]
Time for rethink?

**Comment by maxbachmann** [comment]
oh ... yeah that was a good idea

**Comment by maxbachmann** [comment]
@philipp2310 I updated the dateTimeYear module to use babel, so it should work now on the alpha3 branch
https://github.com/project-alice-powered-by-snips/ProjectAliceModules/commit/93e9719b78b774f28ed56a63a288e469ffe38f53
