### ISSUE TITLE
Exception while recording wakeword

### ISSUE THREAD

**Issue by glueckself** [project-alice-powered-by-snips/ProjectAlice#76]
Hi!

I hope that I don't become annoying posting one issue after the other, but anyway, here's a new one:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alice/ProjectAlice/venv/lib/python3.7/site-packages/paho/mqtt/client.py", line 2913, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/home/alice/ProjectAlice/venv/lib/python3.7/site-packages/paho/mqtt/client.py", line 1578, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/home/alice/ProjectAlice/venv/lib/python3.7/site-packages/paho/mqtt/client.py", line 1072, in loop
    rc = self.loop_read(max_packets)
  File "/home/alice/ProjectAlice/venv/lib/python3.7/site-packages/paho/mqtt/client.py", line 1374, in loop_read
    rc = self._packet_read()
  File "/home/alice/ProjectAlice/venv/lib/python3.7/site-packages/paho/mqtt/client.py", line 2071, in _packet_read
    rc = self._packet_handle()
  File "/home/alice/ProjectAlice/venv/lib/python3.7/site-packages/paho/mqtt/client.py", line 2560, in _packet_handle
    return self._handle_publish()
  File "/home/alice/ProjectAlice/venv/lib/python3.7/site-packages/paho/mqtt/client.py", line 2759, in _handle_publish
    self._handle_on_message(message)
  File "/home/alice/ProjectAlice/venv/lib/python3.7/site-packages/paho/mqtt/client.py", line 2902, in _handle_on_message
    callback(self, self._userdata, message)
  File "/home/alice/ProjectAlice/core/server/MqttManager.py", line 287, in onSnipsCaptured
    SuperManager.getInstance().broadcast(method='onCaptured', exceptions=[self.name], propagateToModules=True, session=session)
  File "/home/alice/ProjectAlice/core/base/SuperManager.py", line 176, in broadcast
    func(*args, **kwargs)
  File "/home/alice/ProjectAlice/core/voice/WakewordManager.py", line 64, in onCaptured
    self._workAudioFile()
  File "/home/alice/ProjectAlice/core/voice/WakewordManager.py", line 131, in _workAudioFile
    self.wakeword.getSample().close()
  File "/usr/lib/python3.7/wave.py", line 445, in close
    self._ensure_header_written(0)
  File "/usr/lib/python3.7/wave.py", line 463, in _ensure_header_written
    raise Error('# channels not specified')
wave.Error: # channels not specified
```

I'm running the alpha2 branch, ec1fc21d2f15337dbe75e77afeddb162194ad842.
I was doing the initial Alice dialogue ("Welcome to Project Alice...") and wanted to record a custom wakeword. I don't understand the code nor what should be happening good enough to describe the problem any more detailed than what the exception says - number of channels not specified.

Please let me know if I can help somehow.

Thanks!

**Comment by glueckself** [comment]
I'm sorry, 054858a doesn't fix this bug, I've just tested it.
My best guess (maybe far fetched) is that the object returned by `self.wakeword.getSample()` doesn't have channels set. Something like `self.wakeword.getSample().setChannels(1)`?

**Comment by Psychokiller1888** [comment]
What hardware are you using?

**Comment by glueckself** [comment]
The mic is a conference USB microphone (TONOR Professional whatever), pulseaudio says it's s16le 1ch 48kHz. pulseaudio resamples it down to 16kHz for snips-satellite (=s16le 1ch 16kHz). I don't know what happens after that.

Just tested cedaa70, still throws the exception.

**Comment by glueckself** [comment]
Enough edits, sorry...

Here are my changes
```diff
diff --git a/core/voice/WakewordManager.py b/core/voice/WakewordManager.py
index 50124ed..a5f232a 100644
--- a/core/voice/WakewordManager.py
+++ b/core/voice/WakewordManager.py
@@ -129,8 +129,9 @@ class WakewordManager(Manager):
                self._state = WakewordManagerState.TRIMMING
 
                sample = self.wakeword.getSample()
-               sample.setnchannels(sample.getnchannels() or 1)
-               sample.setframerate(sample.getframerate() or 22050)
+               sample.setnchannels(1)
+               sample.setframerate(22050)
+               sample.setsampwidth(2)
                sample.close()
 
                filepath = self.wakeword.getSamplePath()
```

**Comment by Psychokiller1888** [comment]
Yes, but setchan 1 is pecific to you as well as te framerate...

**Comment by glueckself** [comment]
Ok? I though they should match either the of snips-satellite(/snips-audio-server) or the input to whatever is doing the training), because those were your default values in cedaa70, I only removed the calls to the get methods to prevent them throwing exceptions.

Have you managed to reproduce the bug? If it's really something specific to my setup, then I'm sorry for creating this issue.

**Comment by Psychokiller1888** [comment]
Thing is they should be taken from the packets sent over mqtt. I can't say why the packets aren't containing them for you. I have tried yesterday the entire procedure and I could capture the wake word at first, with aiy

**Comment by glueckself** [comment]
I see, well, sorry to bother you.
I'll try to find the cause and I'll let you know.
If I hit a wall or have some questions, can I ask you for help?

**Comment by Psychokiller1888** [comment]
I doesn't bother me :) What bothers me is that you have a problem and I can't seem to find a solution to fix it :)

Did you try the latest push I made? It reads the default values from your config file

**Comment by glueckself** [comment]
Don't let it get to you :) My setup is unnecessarily complicated, so yeah, it might hit a few rough edges in Alice. Maybe the only thing you'd need to find the cause would be a SSH session into my devices, but that's one thing I can't help you with :)

Yes, I'm running 0f0da318dd4e0c3cd37cb5581b6968f0ef48954a.
I'll sprinkle a few print()s around and see if I can find anything. Also, snips-watch can save the transmitted audio files, maybe I'll find something there.

I'm not sure that the values would cause problems in the TRIMMING state. When setting the values manually, the 1_raw.wav file is 44 bytes. I think that has a connection with the problem.
My gut tells me that the object returned by getSample() in _workAudioFile() is somehow not right, but I don't know how or why.
From what I understand, the object is created in addASample() and filled in onAudioFrame(). So it should be okay when reaching _workAudioFile(), where it's written to disk (getSample().close(); that's where the initial exception was raised) and then reopened again as a AudioSegment (where the current exception is raised).
Not having the values at .close() makes me think that either onAudioFrame() receives something it can't handle or somehow the object gets messed up.

**Comment by Psychokiller1888** [comment]
is the sample rate in your config.py set @ 22050?

**Comment by glueckself** [comment]
I had the default value (44100), just tried it with 22050, doesn't help, still crashes in getnchannels.

**Comment by Psychokiller1888** [comment]
ok, let's change the way we handle the problem

**Comment by glueckself** [comment]
I have the problem: onAudioFrame() is not called.
Don't know why yet, but not receiving audio fits both the exceptions: the missing values and, when provided manually, the empty wav file.
I'll try to find out why the WakewordManager doesn't receive anything, because I can interact with Alice otherwise (Name, Confirming name, wanting to record wake word, MpdClient yesterday)

**Comment by glueckself** [comment]
I think you can revert all of the changes you made for this issue.
If you like, you can add something to check the RECORDING state was successful (=there is data in in the sample, if it's possible to find that out) before starting the TRIMMING state.

**Comment by glueckself** [comment]
I've pinpointed the problem: it's the site id (again).
When I changed the bind to "default@mqtt" on both my server (the main unit) and my laptop (the satellite) onAudioFrame started receiving data.

**Comment by glueckself** [comment]
You'll actually need to revert to only calling .getSample().close(), because now that's data inside the sample, it raises an exception when trying to set the values.

**Comment by glueckself** [comment]
Ok, I still have problems (the dialog session times out, ...), but those might be caused by the delay over the VPN. I'll try that again when I'm home.

Again, thanks for your time and your support!

**Comment by Psychokiller1888** [comment]
Ok, added a check to see if any data was actually captured. I'm closing this one
