### ISSUE TITLE
Error installing module

### ISSUE THREAD

**Issue by mjlill** [project-alice-powered-by-snips/ProjectAlice#80]
[ModuleManager] Module Minigames does not comply to "notModule" condition, required "['maxbachmann/RockPaperScissors']"
[ModuleManager] Error checking for module install: 'str' object has no attribute 'append'
Oops?

**Comment by Psychokiller1888** [comment]
First one says it all, you can't have both modules

The second one, can't repro

**Comment by maxbachmann** [comment]
```
[ModuleManager] Module Telemetry does not comply to "activeManager" condition, required "['TelemetryManager']"
[ModuleManager] Error checking for module install: 'str' object has no attribute 'append'
```
I can confirm the second one happening

**Comment by Psychokiller1888** [comment]
We really need to attach a stacktrace. Will work on that so that alpha 3 ships with stacktraces

**Comment by Psychokiller1888** [comment]
Should be fixed, never saw it anymore
