### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Psychokiller1888** [project-alice-powered-by-snips/ProjectAlice#9]
The core modules need complete translation to EN, FR and DE before alpha. The other modules don't have to be translated just yet

Theses modules are:

- AliceCore
- AliceSatellite
- ContextSensitive
- Customisation
- DateDayTimeYear
- RedQueen

**Comment by mauriciolanda4** [comment]
Do you need a Spanish translation? I could do that if needed

**Comment by Psychokiller1888** [comment]
That would be awesome! Snips support ES so yeah, would be useful! Let's meet on our discord server!

**Comment by mauriciolanda4** [comment]
Could you send me a link to the discord server?

**Comment by jokerigno** [comment]
Hi, I'm a TOTAL NOOB but I would help to translate to IT. How can I start?

**Comment by Psychokiller1888** [comment]
@mauriciolanda4 the link is on the main github page

@jokerigno IT is not made yet and is supported by Snips, would be great! You need to fork the modules repo https://github.com/project-alice-powered-by-snips/ProjectAliceModules and start by translating the modules by ProjectAlice that are core modules. There are a few files on the core side also, such as: https://github.com/project-alice-powered-by-snips/ProjectAlice/tree/master/system/manager . Whenever you feel like sharing, open a Pull Request for me to merge your work

**Comment by monschiTee** [comment]
I will try to translate AliceSatellite into German

**Comment by maxbachmann** [comment]
all core modules are now translated to en, fr and de
