### ISSUE TITLE
no playback hardware devices

### ISSUE THREAD

**Issue by LazzaWA** [project-alice-powered-by-snips/ProjectAlice#96]
Installed Project alice as per Wiki instructions. I have a pi3b+ with respeaker 4 and a speaker plugged into the 3.5 jack

Setup seemed to of worked as i can see modules installed in the snips console. There seems to be no major error in the terminal other than a warning that there's "no user found in the database" which is understandable as  i havent heard her speak yet and i can't trigger her using the hotword "hey snips"

in the command line if i use :

`pi@projectalice:~ $ aplay -L`
i get 

> null
    Discard all samples (playback) or generate zero samples (capture)
default
playback
ac108

`pi@projectalice:~ $ aplay -l`

>**** List of PLAYBACK Hardware Devices ****

**NOTE: There's nothing listed under playback devices**

`pi@projectalice:~ $ speaker-test -c2`

>speaker-test 1.1.3
Playback device is default
Stream parameters are 48000Hz, S16_LE, 2 channels
Using 16 octaves of pink noise
ALSA lib pcm_hw.c:1713:(_snd_pcm_hw_open) Invalid value for card
Playback open error: -19,No such device

and finally
 
`arecord -L`

>pi@projectalice:~ $ arecord -L
null
    Discard all samples (playback) or generate zero samples (capture)
default
playback
dmixed
ac108
multiapps
sysdefault:CARD=seeed4micvoicec
    seeed-4mic-voicecard,
    Default Audio Device
dmix:CARD=seeed4micvoicec,DEV=0
    seeed-4mic-voicecard,
    Direct sample mixing device
dsnoop:CARD=seeed4micvoicec,DEV=0
    seeed-4mic-voicecard,
    Direct sample snooping device
hw:CARD=seeed4micvoicec,DEV=0
    seeed-4mic-voicecard,
    Direct hardware device without any conversions
plughw:CARD=seeed4micvoicec,DEV=0
    seeed-4mic-voicecard,
    Hardware device with all software conversions

Appreciate any suggestion before i go trying to manually reinstall the respeaker ?

**Comment by Psychokiller1888** [comment]
So the respeaker is correctly installed

Maybe a `sudo raspi-config` to force the audio playback on the 3.5mm jack?

**Comment by LazzaWA** [comment]
Thanks , however that wasn't the issue, i have no microphone either (can't record anything or say "hey snips") so its more than just a 3.5mm jack setting i'd suspect.

I decided to wipe everything and try loading everything from scratch again and now it loads nothing at all and only does the below  in the logs

> tail: ProjectAlice/var/logs/logs.log: file truncated
2019-10-13 08:09:33,807 [MainThread] - [INFO] - Starting Project Alice initializ                                                                                        er
2019-10-13 08:09:33,811 [MainThread] - [INFO] - Starting up project Alice core
2019-10-13 08:09:34,112 [MainThread] - [ERROR] - An unhandled exception occured
2019-10-13 08:09:34,115 [MainThread] - [ERROR] - - Traceback: Traceback (most re                                                                                        cent call last):
  File "main.py", line 90, in <module>
    main()
  File "main.py", line 76, in main
    projectAlice = ProjectAlice()
  File "/home/pi/ProjectAlice/core/ProjectAlice.py", line 16, in __init__
    self._superManager.initManagers()
  File "/home/pi/ProjectAlice/core/base/SuperManager.py", line 128, in initManag                                                                                        ers
    from core.interface.WebInterfaceManager import WebInterfaceManager
  File "/home/pi/ProjectAlice/core/interface/WebInterfaceManager.py", line 6, in                                                                                         <module>
    from flask import Flask, send_from_directory
ModuleNotFoundError: No module named 'flask'


Despite being keen to see what all your  hard work was all about i've decided this is to advanced for me anyway as i wont be able to write my own modules to work with my homeassistant. So going to go back to using snips for now. 
Thanks anyway

You can delete this thread if you like. Cheers

**Comment by Psychokiller1888** [comment]
Sorry for that, but that's the harsh alpha reality :)
The error you see is clear, flask is not installed, you just need to install it in your venv
```
cd ~ProjectAlice
./venv/bin/pip3 install Flask
./venv/bin/pip3 install flask-classful
```
