### ISSUE TITLE
trashing assistant do to error from snips

### ISSUE THREAD

**Issue by mjlill** [project-alice-powered-by-snips/ProjectAlice#97]
Several times I have had an error occur from the snips server that leaves a downloaded assistant in an incomplete state.  The recovery process is long and painful which could be avoided if the current functional assistant were to be saved prior to any changes.  If there was an error detected while doing the skills building, training and or downloading that the saved assistant could be recovered so that Alice doesn't become crippled would be great.  Of course she would also announce the failure :)

**Comment by Psychokiller1888** [comment]
when exactly does this happen? Do you get a "Assistant download failed" message or do you get the "Assistant xxxxxx trained and downloaded"?
